from __future__ import annotations

"""
v9_of — Feature schema version derived from actual infer_feature_cols() output.

Generated 2026-03-03 from run 20260303_175837 (signals:of:inputs, 1771 joined signals).

v9_of = complete set of numeric features actually present in current signal stream.
Replaces infer_feature_cols() auto-detection with a deterministic, pinned registry.

Coverage: 128 numeric indicators (vs v7_of=128 nominal but only 25 matching), 
           + direction/bucket/hour/dow one-hots → 168 total feature_cols.
"""


SCHEMA_HASH = "1c813fb2b468"



# Numeric feature keys (indicator field names, without "f_" prefix)
# Derived from actual infer_feature_cols() on signals:of:inputs, 2026-03-03
V9_OF_NUMERIC_KEYS: list[str] = [
    "abs_lvl_calib_n",
    "abs_lvl_eff_quote_th",
    "abs_lvl_min_quote_delta",
    "abs_lvl_ready",
    "atr",
    "atr_age_ms",
    "atr_bad",
    "atr_bps",
    "atr_bps_exec",
    "atr_candidates_n",
    "atr_cons_ok",
    "atr_consistency",
    "atr_fees_rocket_mult",
    "atr_fees_th_bps",
    "atr_fees_tp1_share",
    "atr_floor_t0_bps",
    "atr_floor_t1_bps",
    "atr_floor_t2_bps",
    "atr_floor_tier",
    "atr_jump_count_window",
    "atr_sanity_ok",
    "atr_ts_ms",
    "atr_unified_th_bps",
    "atr_used_last_good",
    "book_evidence_allowed",
    "book_health_ok",
    "book_health_veto_book_evidence",
    "book_rate_hz",
    "book_ts_gap_ms",
    "burst_churn",
    "burst_cr_ema",
    "burst_ctr",
    "burst_exc",
    "burst_ha_lam",
    "burst_pen",
    "burst_tr_ema",
    "burst_veto",
    "burst_z",
    "conf_rsi_agree",
    "confidence",
    "cooldown_hit_rate",
    "cooldown_hit_rate_ema",
    "cvd_ema",
    "cvd_jump_events_total",
    "cvd_median_abs_delta_usd",
    "cvd_quarantine_active",
    "cvd_quarantine_until_ms",
    "cvd_reset_skipped_bad_time",
    "cvd_resets",
    "cvd_slope",
    "cvd_tick",
    "data_health",
    "data_health_shadow_only",
    "data_health_veto_book_evidence",
    "delta",
    "delta_mad",
    "delta_med",
    "delta_n",
    "delta_notional_usd",
    "delta_robust_z",
    "delta_tick",
    "div_match",
    "div_match_fallback",
    "dn_t1_usd",
    "dn_tier",
    "dn_tier_active",
    "dn_tier_threshold",
    "dn_usd",
    "dq_veto_suppressed",
    "ema_delta",
    "eta_fill_sec",
    "exec_fill_pen",
    "exec_pen",
    "exec_risk_bps",
    "exec_risk_norm",
    "exec_risk_ref_bps",
    "expected_slippage_bps",
    "fill_prob_p_base",
    "fill_prob_p_wait",
    "fill_prob_proxy",
    "fp_edge_absorb",
    "fp_edge_age_ms",
    "hour_of_week",
    "iceberg_avg_qty",
    "iceberg_refresh",
    "iceberg_strict",
    "liq_depth_usd_min_5",
    "liq_depth_warn",
    "liq_ofi_align",
    "liq_pressure_boost",
    "liq_pressure_pen",
    "liq_pressure_veto",
    "liq_q_align",
    "liq_rate_warn",
    "liq_score",
    "liq_spread_crit",
    "liq_spread_warn",
    "liqmap_gate_adverse_peak_usd",
    "liqmap_gate_favorable_peak_usd",
    "liqmap_gate_reward_bps",
    "liqmap_gate_risk_bps",
    "liqmap_gate_rr",
    "liqmap_gate_shadow_veto",
    "liqmap_gate_soft",
    "liqmap_gate_veto",
    "liqmap_ok",
    "liqmap_sl_base_bps",
    "liqmap_sl_reco_bps",
    "liqmap_sl_widen_needed",
    "liqmap_sl_widen_ratio",
    "liquidity_scale",
    "now_ts_ms_used",
    "obi",
    "obi_stable",
    "obi_z",
    "of_base_score",
    "of_confirm_have_need_ratio",
    "of_confirm_ok",
    "of_confirm_ok_soft",
    "of_confirm_score",
    "of_score_final",
    "of_score_final_raw",
    "ofi",
    "ofi_age_ms",
    "ofi_dir_ok",
    "ofi_stability_score",
    "ofi_stable",
    "ofi_stable_secs",
]


def get_v9_of_numeric_keys() -> list[str]:
    """Return sorted list of numeric indicator keys for v9_of."""
    return list(V9_OF_NUMERIC_KEYS)
