
rca_services = """
  scanner-route-incident-rca-mirror-rca-winner-apply-apply-evaluator-v3-31:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_evaluator_v3_31"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_PORT:-9956}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_RUN_EVERY_SEC=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_RUN_EVERY_SEC:-300}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_WINDOW_MIN=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_WINDOW_MIN:-10080}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_LOOKBACK_COUNT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_LOOKBACK_COUNT:-500}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_EXPOSURES=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_EXPOSURES:-10}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_FEEDBACK=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_FEEDBACK:-5}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_RESULT_COVERAGE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_RESULT_COVERAGE:-0.30}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_FEEDBACK_COVERAGE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_FEEDBACK_COVERAGE:-0.20}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_QUALITY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_QUALITY:-0.55}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_USEFULNESS=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_USEFULNESS:-0.60}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_ACCEPTED_RATE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_ACCEPTED_RATE:-0.60}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_SCORE_MARGIN=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_MIN_SCORE_MARGIN:-0.05}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_INCUMBENT_ARM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_INCUMBENT_ARM:-deterministic}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_EVALUATOR_PORT:-9956}:9956"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-controller-v3-32:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_apply_controller_v3_32"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_PORT:-9957}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_ADVISORY_ONLY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_ADVISORY_ONLY:-1}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_EXECUTOR_MODE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_EXECUTOR_MODE:-DRY_RUN}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_STRATEGY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_STRATEGY:-SHADOW_PRIMARY}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_COOLDOWN_SEC=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_COOLDOWN_SEC:-21600}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_MIN_WINNER_SCORE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_MIN_WINNER_SCORE:-0.0}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_ALLOW_ARMS_JSON=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_ALLOW_ARMS_JSON:-["vertex_candidate","local_fallback_candidate"]}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_CONTROLLER_PORT:-9957}:9957"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-verification-v3-33:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_verification_loop_v3_33"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_PORT:-9958}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_RUN_EVERY_SEC=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_RUN_EVERY_SEC:-300}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_MIN_EXPOSURES=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_MIN_EXPOSURES:-5}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_MIN_PRIMARY_MATCH_RATE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_MIN_PRIMARY_MATCH_RATE:-0.80}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_MAX_UNEXPECTED_PRIMARY_RATE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_MAX_UNEXPECTED_PRIMARY_RATE:-0.20}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_MAX_SHADOW_RATE_SINGLE_ARM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_MAX_SHADOW_RATE_SINGLE_ARM:-0.05}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_REQUIRE_POLICY_MATCH=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_REQUIRE_POLICY_MATCH:-1}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_ADVISORY_ONLY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_ADVISORY_ONLY:-1}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_EXECUTOR_MODE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_EXECUTOR_MODE:-DRY_RUN}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_ROLLBACK_COOLDOWN_SEC=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_ROLLBACK_COOLDOWN_SEC:-21600}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_VERIFICATION_PORT:-9958}:9958"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-slo-v3-34:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_slo_analytics_v3_34"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_SLO_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_SLO_PORT:-9959}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_SLO_PORT:-9959}:9959"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    volumes:
      - ./python-worker:/app
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-retry-v3-34:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_retry_controller_v3_34"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_RETRY_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_RETRY_PORT:-9960}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_RETRY_MAX_ATTEMPTS=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_RETRY_MAX_ATTEMPTS:-2}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_RETRY_BACKOFF_SEC=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_RETRY_BACKOFF_SEC:-120}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_RETRY_PORT:-9960}:9960"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-escalations-v3-34:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_auto_escalation_summarizer_v3_34"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_ESCALATIONS_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_ESCALATIONS_PORT:-9961}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_ESCALATIONS_PORT:-9961}:9961"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-governance-incident-bundles-v3-35:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_governance_incident_bundle_builder_v3_35"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_PORT:-9962}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_LOOKBACK_COUNT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_LOOKBACK_COUNT:-50}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_RECENT_WINDOW_MIN=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_RECENT_WINDOW_MIN:-240}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_ONLY_SEVERITY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_ONLY_SEVERITY:-warning,critical}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_TRIGGER_ON_APPLY_DECISIONS=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_TRIGGER_ON_APPLY_DECISIONS:-APPLY_PRIMARY_ARM_SHADOW,APPLY_SINGLE_ARM}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_PORT:-9962}:9962"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-governance-rca-bridge-v3-36:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_governance_bundle_rca_bridge_v3_36"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_PORT:-9963}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_MODE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_MODE:-AUTO}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_REQUIRE_VERTEX_DEGRADED_FOR_LOCAL=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_REQUIRE_VERTEX_DEGRADED_FOR_LOCAL:-1}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_MAX_BUNDLE_BYTES=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_MAX_BUNDLE_BYTES:-131072}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_MAX_PROMPT_CHARS=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_MAX_PROMPT_CHARS:-12000}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_STREAM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_STREAM:-stream:ml:route_incident_rca_mirror_rca_winner_apply_apply_governance_vertex_rca_requests}
      - ML_LOCAL_FALLBACK_REQUESTS_STREAM=${ML_LOCAL_FALLBACK_REQUESTS_STREAM:-stream:ml:local_fallback_requests}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_STREAM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_INCIDENT_BUNDLES_STREAM:-stream:ml:route_incident_rca_mirror_rca_winner_apply_apply_governance_incident_bundles}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_VERTEX_HEALTH_HASH=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_VERTEX_HEALTH_HASH:-metrics:ml:vertex_health:last}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_RCA_BRIDGE_PORT:-9963}:9963"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-governance-vertex-rca-v3-37:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_governance_vertex_rca_consumer_v3_37"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_PORT:-9964}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_HANDLER_MODE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_HANDLER_MODE:-DETERMINISTIC}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_PORT:-9964}:9964"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-governance-vertex-governance-v3-37:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_governance_vertex_feedback_governor_v3_37"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_PORT:-9965}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MIN_SAMPLES=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MIN_SAMPLES:-10}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MIN_AVG_QUALITY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MIN_AVG_QUALITY:-0.55}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MIN_AVG_USEFULNESS=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MIN_AVG_USEFULNESS:-0.60}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MIN_ACCEPTED_RATE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MIN_ACCEPTED_RATE:-0.60}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MAX_LOW_QUALITY_RATE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_MAX_LOW_QUALITY_RATE:-0.35}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_VERTEX_RCA_GOVERNANCE_PORT:-9965}:9965"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-governance-experiment-v3-38:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_governance_experiment_harness_v3_38"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_PORT:-9966}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_MODE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_MODE:-SHADOW}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_HASH_SALT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_HASH_SALT:-route_incident_rca_mirror_rca_winner_apply_apply_governance_v3_38}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_ARM_WEIGHTS_JSON=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_ARM_WEIGHTS_JSON:-{"deterministic":70,"vertex_candidate":20,"local_fallback_candidate":10}}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_PRIMARY_ARM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_PRIMARY_ARM:-deterministic}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_SHADOW_ARMS_JSON=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_SHADOW_ARMS_JSON:-["vertex_candidate","local_fallback_candidate"]}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_ALLOW_SEVERITIES=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_ALLOW_SEVERITIES:-warning,critical}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_MAX_BUNDLE_BYTES=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_MAX_BUNDLE_BYTES:-131072}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_DETERMINISTIC_STREAM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_DETERMINISTIC_STREAM:-stream:ml:route_incident_rca_mirror_rca_winner_apply_apply_governance_vertex_rca_requests}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_VERTEX_STREAM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_VERTEX_STREAM:-stream:ml:route_incident_rca_mirror_rca_winner_apply_apply_governance_vertex_rca_candidate_requests}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_LOCAL_STREAM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_LOCAL_STREAM:-stream:ml:route_incident_rca_mirror_rca_winner_apply_apply_governance_local_rca_candidate_requests}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EXPERIMENT_PORT:-9966}:9966"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-governance-evaluator-v3-39:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_governance_evaluator_v3_39"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_PORT:-9967}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_RUN_EVERY_SEC=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_RUN_EVERY_SEC:-300}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_WINDOW_MIN=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_WINDOW_MIN:-10080}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_LOOKBACK_COUNT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_LOOKBACK_COUNT:-500}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_EXPOSURES=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_EXPOSURES:-10}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_FEEDBACK=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_FEEDBACK:-5}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_RESULT_COVERAGE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_RESULT_COVERAGE:-0.30}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_FEEDBACK_COVERAGE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_FEEDBACK_COVERAGE:-0.20}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_QUALITY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_QUALITY:-0.55}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_USEFULNESS=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_USEFULNESS:-0.60}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_ACCEPTED_RATE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_ACCEPTED_RATE:-0.60}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_SCORE_MARGIN=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_MIN_SCORE_MARGIN:-0.05}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_INCUMBENT_ARM=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_INCUMBENT_ARM:-deterministic}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_EVALUATOR_PORT:-9967}:9967"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra

  scanner-route-incident-rca-mirror-rca-winner-apply-apply-governance-apply-controller-v3-40:
    build: { context: ., dockerfile: python-worker/Dockerfile.gpu }
    command: ["python", "-m", "orderflow_services.route_incident_rca_mirror_rca_winner_apply_apply_governance_apply_controller_v3_40"]
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_WORKER_URL:-redis://redis-worker-1:6379/0}
      - DATABASE_URL=${POSTGRES_URL:-postgresql://trading:trading_pass@scanner-postgres:5432/scanner_analytics}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_PORT=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_PORT:-9968}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_ADVISORY_ONLY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_ADVISORY_ONLY:-1}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_EXECUTOR_MODE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_EXECUTOR_MODE:-DRY_RUN}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_STRATEGY=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_STRATEGY:-SHADOW_PRIMARY}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_COOLDOWN_SEC=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_COOLDOWN_SEC:-21600}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_MIN_WINNER_SCORE=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_MIN_WINNER_SCORE:-0.0}
      - ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_ALLOW_ARMS_JSON=${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_ALLOW_ARMS_JSON:-["vertex_candidate","local_fallback_candidate"]}
    ports: ["${ML_ROUTE_INCIDENT_RCA_MIRROR_RCA_WINNER_APPLY_APPLY_GOVERNANCE_APPLY_CONTROLLER_PORT:-9968}:9968"]
    depends_on:
      redis-worker-1:
        condition: service_healthy
    networks:
      - scanner-core
      - scanner-infra
"""

with open("docker-compose-python-workers.yml", "a") as f:
    f.write(rca_services)

