import re

_GO_TO_PYTHON = {
    "TickTPL": "TICK_TPL",
    "BookTPL": "BOOK_TPL",
    "CryptoOrderflowTPL": "CRYPTO_ORDERFLOW_TPL",
    "SignalAuditTPL": "SIGNAL_AUDIT_TPL",
    "EventsMicrobarTPL": "EVENTS_MICROBAR_TPL",
    "OFGateMetrics": "OF_GATE_METRICS",
    "OFGateMetricsQuarantine": "OF_GATE_METRICS_QUARANTINE",
    "TickTime": "TICK_TIME",
    "MLConfirmMetrics": "ML_CONFIRM_METRICS",
    "MLOutcomeMetrics": "ML_OUTCOME_METRICS",
    "CryptoRaw": "CRYPTO_RAW",
    "CryptoRejected": "CRYPTO_REJECTED",
    "OFConfirm": "OF_CONFIRM",
    "OFInputs": "OF_INPUTS",
    "SignalOutbox": "SIGNAL_OUTBOX",
    "SignalDLQ": "SIGNAL_DLQ",
    "SignalOutboxRetrySchedule": "SIGNAL_OUTBOX_RETRY_SCHEDULE",
    "SignalOutcomes": "SIGNAL_OUTCOMES",
    "ConfScores": "CONF_SCORES",
    "ConfQuarantine": "CONF_QUARANTINE",
    "SignalsUnified": "SIGNALS_UNIFIED",
    "NotifyTelegram": "NOTIFY_TELEGRAM",
    "NotifyTelegramCrit": "NOTIFY_TELEGRAM_CRIT",
    "NotifyTelegramPage": "NOTIFY_TELEGRAM_PAGE",
    "OrdersExec": "ORDERS_EXEC",
    "OrdersQueueBinance": "ORDERS_QUEUE_BINANCE",
    "OrdersQueueMT5": "ORDERS_QUEUE_MT5",
    "OrdersIntentBinance": "ORDERS_INTENT_BINANCE",
    "OrdersQueueBinanceProcessing": "ORDERS_QUEUE_BINANCE_PROCESSING",
    "OrdersQueueBinanceDLQ": "ORDERS_QUEUE_BINANCE_DLQ",
    "OrdersQueueBinanceMirror": "ORDERS_QUEUE_BINANCE_MIRROR",
    "BotCallbacks": "BOT_CALLBACKS",
    "OrdersQueue": "ORDERS_QUEUE",
    "EventsTrades": "EVENTS_TRADES",
    "EventsMicrobarClosed": "EVENTS_MICROBAR_CLOSED",
    "EventsMicrobarMajors": "EVENTS_MICROBAR_MAJORS",
    "EventsBboTs": "EVENTS_BBO_TS",
    "EventsConfCal": "EVENTS_CONF_CAL",
    "DecisionSnapshot": "DECISION_SNAPSHOT",
    "TradesClosed": "TRADES_CLOSED",
    "TradesCloseWait": "TRADES_CLOSE_WAIT",
    "TradesPostSL": "TRADES_POST_SL",
    "DecisionsFinal": "DECISIONS_FINAL",
    "CandleDataStream": "CANDLES_DATA",
    "CandleDataGroup": "CANDLES_CONSUMER_GROUP",
    "TBLabels": "TB_LABELS",
    "TBTickPrefix": "TB_TICK_PREFIX",
    "OFQuarantine": "OF_QUARANTINE",
    "TickSideQuarantine": "TICK_SIDE_QUARANTINE",
    "BurstAudit": "BURST_AUDIT",
    "EntryAudit": "ENTRY_AUDIT",
    "SMTSetup": "SMT_SETUP",
    "SMTSnapshot": "SMT_SNAPSHOT",
    "EdgeGateEvents": "EDGE_GATE_EVENTS",
    "EntryCandidate": "ENTRY_CANDIDATE",
    "SignalBridgeNotify": "SIGNAL_BRIDGE_NOTIFY",
    "SignalBridgeManual": "SIGNAL_BRIDGE_MANUAL",
    "OpsAlerts": "OPS_ALERTS",
    "ABSuggestions": "AB_SUGGESTIONS",
    "PolicyEvents": "POLICY_EVENTS",
    "DLQSignals": "DLQ_SIGNALS",
    "DLQTicks": "DLQ_TICKS",
    "DLQEvents": "DLQ_EVENTS",
    "DLQTradeMonitor": "DLQ_TRADE_MONITOR",
    "SignalAckDLQ": "SIGNAL_ACK_DLQ",
    "DLQBookDeltas": "DLQ_BOOK_DELTAS",
    "NewsRaw": "NEWS_RAW",
    "NewsAnalysis": "NEWS_ANALYSIS",
    "NewsSignals": "NEWS_SIGNALS",
    "CalendarEvents": "CALENDAR_EVENTS",
    "ConfigSymbols": "CONFIG_SYMBOLS",
    "ExecHealthFreezeEvents": "EXEC_HEALTH_FREEZE_EVENTS",
    "MLReplayInputs": "ML_REPLAY_INPUTS",
    "AggHubControl": "AGG_HUB_CONTROL",
    "LiqEvt": "LIQ_EVT",
    "LiqEvtQuarantine": "LIQ_EVT_QUARANTINE",
    "Ticker24h": "TICKER_24H",
    "FundingRate": "FUNDING_RATES",
    "Symbols": "SYMBOLS",
    "Volatility": "VOLATILITY",
    "VolatilityRange": "VOLATILITY_RANGE",
    "TopGainers": "TOP_GAINERS",
    "TopLosers": "TOP_LOSERS",
    "BybitTicker24h": "BYBIT_TICKER_24H",
    "BybitFundingRate": "BYBIT_FUNDING_RATE",
    "WSNewPairs": "WS_NEW_PAIRS",
    "WSNewPairsStream": "WS_NEW_PAIRS_STREAM",
    "OrdersStatePrefix": "ORDERS_STATE",
    "OrdersActiveSymbolSIDPrefix": "ORDERS_ACTIVE_SYMBOL_SID",
    "OrdersQuarantineSIDs": "ORDERS_QUARANTINE_SIDS",
    "UserStreamCachePrefix": "USER_STREAM_CACHE",
    "LiqmapSnapshot": "LIQMAP_SNAPSHOT",
    "MicrobarSymbolsSet": "MICROBAR_SYMBOLS_SET",
    "MicrobarPerSymbol": "MICROBAR_PER_SYMBOL",
    "AtrBadTotalPrefix": "ATR_BAD_TOTAL_PREFIX",
    "CvdJumpTotalPrefix": "CVD_JUMP_TOTAL_PREFIX",
    "LcbKeysSet": "LCB_KEYS_SET",
    "LcbWinnerChangesPrefix": "LCB_WINNER_CHANGES_PREFIX",
    "CfgOverridesPrefix": "CFG_OVERRIDES_PREFIX",
    "DerivContextPrefix": "DERIV_CONTEXT_PREFIX",
    "SignalKeyPrefix": "SIGNAL_KEY_PREFIX",
    "SignalSnapPrefix": "SIGNAL_SNAP",
    "OutboxMetaPrefix": "OUTBOX_META",
    "NotifySignalCounter": "NOTIFY_SIGNAL_COUNTER",
    "NewsRecoMap": "NEWS_RECO_MAP",
}

def to_snake(name: str) -> str:
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).upper()

fails = []
for k, v in _GO_TO_PYTHON.items():
    gen = to_snake(k)
    if gen != v:
        fails.append((k, v, gen))

for f in fails:
    print(f"{f[0]}: expected {f[1]}, got {f[2]}")
print(f"Total fails: {len(fails)}")

