from __future__ import annotations

import json

import redis

from services.signal_publisher import PublishSinks, SignalPublisher
from utils.time_utils import get_ny_time_millis


class FakeRedis:
    def __init__(self):
        self.kv = {}
        self.streams = {}
        self.lists = {}
        self.counters = {}
        self.raise_on = {}  # op -> exception

    def incr(self, key: str):
        self.counters[key] = int(self.counters.get(key, 0)) + 1
        return self.counters[key]

    def set(self, key: str, val: str, ex: int = 0):
        if "set" in self.raise_on:
            raise self.raise_on["set"]
        self.kv[key] = val
        return True

    def xadd(self, stream: str, fields: dict, maxlen: int = 0, approximate: bool = True):
        if "xadd" in self.raise_on:
            raise self.raise_on["xadd"]
        self.streams.setdefault(stream, []).append(fields)
        return "1-0"

    def lpush(self, key: str, val: str):
        if "lpush" in self.raise_on:
            raise self.raise_on["lpush"]
        self.lists.setdefault(key, []).insert(0, val)
        return len(self.lists[key])


class DummyOrderBuilder:
    def build_order_from_signal(self, signal_payload: dict):
        return {"sid": signal_payload.get("signal_id") or signal_payload.get("sid"), "side": signal_payload.get("side")}


def test_publisher_normalizes_ids_side_ts_and_prices():
    r = FakeRedis()
    pub = SignalPublisher(
        redis_client=r,
        sinks=PublishSinks(store_prefix="signals:", raw_stream="raw", notify_stream="notify", orders_queue="orders"),
        source="test",
        metrics_prefix="pub",
        logger=None,
        order_builder=DummyOrderBuilder(),
    )

    payload = {
        "symbol": "BTCUSDT",
        "direction": "LONG",
        "entry": 123.45,
        "confidence": 0.8,
        "ts": get_ny_time_millis(),
    }
    res = pub.publish(payload, symbol="BTCUSDT")
    assert res.ok is True

    # stored payload must have invariants
    # NOTE: signal_id generated by preprocess
    sid = payload.get("signal_id") or payload.get("sid")
    stored = json.loads(r.kv[f"signals:{sid}"])
    assert stored["symbol"] == "BTCUSDT"
    assert int(stored["ts_ms"]) > 0
    assert stored["side"] in ("LONG", "SHORT")
    assert int(stored["side_int"]) in (1, -1)
    assert float(stored["entry_price"]) > 0
    assert float(stored["price"]) > 0
    assert "signal_id" in stored and "sid" in stored

    assert "raw" in r.streams and len(r.streams["raw"]) == 1
    assert "notify" in r.streams and len(r.streams["notify"]) == 1
    assert "orders" in r.lists and len(r.lists["orders"]) == 1


def test_publisher_busyloading_short_circuits():
    r = FakeRedis()
    r.raise_on["set"] = redis.exceptions.BusyLoadingError()

    pub = SignalPublisher(
        redis_client=r,
        sinks=PublishSinks(store_prefix="signals:", raw_stream="raw", notify_stream="notify", orders_queue="orders"),
        source="test",
        metrics_prefix="pub",
        logger=None,
        order_builder=DummyOrderBuilder(),
    )
    payload = {"symbol": "BTCUSDT", "side": "LONG", "entry": 10.0, "ts_ms": get_ny_time_millis()}
    res = pub.publish(payload, symbol="BTCUSDT")
    assert res.ok is False
    assert res.busy_loading is True
    # no further writes
    assert "raw" not in r.streams
    assert "notify" not in r.streams
    assert "orders" not in r.lists


def test_publisher_independent_sinks_fail_open():
    r = FakeRedis()
    r.raise_on["xadd"] = RuntimeError("xadd down")

    pub = SignalPublisher(
        redis_client=r,
        sinks=PublishSinks(store_prefix="signals:", raw_stream="raw", notify_stream="notify", orders_queue="orders"),
        source="test",
        metrics_prefix="pub",
        logger=None,
        order_builder=DummyOrderBuilder(),
    )
    payload = {"symbol": "BTCUSDT", "side": "SHORT", "entry": 11.0, "ts_ms": get_ny_time_millis()}
    res = pub.publish(payload, symbol="BTCUSDT")
    # store + order push should still succeed (xadd fails)
    assert res.ok is True
    assert res.stored is True
    assert res.order_pushed is True
    assert res.raw_written is False
    assert res.notify_written is False
