user default on nopass sanitize-payload ~* &* +@all
user go_worker on #5094224e5fe94408711310410b20c01a7efe9c2c90504600e4aab5548238f0b0 ~* resetchannels &* -@all +ping +xadd +xread +xreadgroup +xack +xgroup +xrevrange +xrange +xlen +xinfo|stream +xinfo|groups +xinfo|consumers +client|setname +client|setinfo +client|id +client|info +client|list
