#!/usr/bin/env python3
from __future__ import annotations

"""P12: ExecHealth freeze-control ACL deployment policy.

Three operations:
  render      — print the deployment contract (ACL SETUSER commands + disable default)
  apply       — apply ACL SETUSER for each user, ACL SAVE, optional ACL LOAD roundtrip check
  check       — drift check: compare ACL LIST vs expected contract

Usage:
  python orderflow_services/exec_health_freeze_acl_policy_v1.py render
  python orderflow_services/exec_health_freeze_acl_policy_v1.py apply [--reload-check]
  python orderflow_services/exec_health_freeze_acl_policy_v1.py check

ENV:
  REDIS_URL                               — Redis connection URL
  EXEC_HEALTH_FREEZE_READER_PASS          — password for reader user
  EXEC_HEALTH_FREEZE_WRITER_PASS          — password for writer user
  EXEC_HEALTH_FREEZE_AUDIT_PASS           — password for audit user
  EXEC_HEALTH_FREEZE_BOOTSTRAP_PASS       — password for bootstrap user
"""

import json
import os
import sys
from typing import Any, Dict, List, Optional, Tuple

from services.orderflow.exec_health_freeze_acl_contract import (
    EXPECTED_ACL_PROFILES,
    EXPECTED_USERS,
    compare_acl,
    is_default_user_disabled,
    normalise_acl_line,
    render_all_setuser_commands,
    render_setuser,
)
from services.orderflow.exec_health_freeze_deploy_contract import (
    assert_runtime_service_env_contract,
    render_sensitive_deploy_env_templates,
)
from services.orderflow.exec_health_freeze_service_identity import ensure_service_identity_sync, render_service_identity_env_templates
from services.orderflow.exec_health_freeze_reconnect_healing import heal_service_identity_sync
from services.orderflow.exec_health_freeze_rollout_gate import assert_rollout_gate_open

try:
    import redis  # type: ignore
except Exception:  # pragma: no cover
    redis = None


# ─── Password substitution ───────────────────────────────────────────────────

_PASS_ENV: Dict[str, str] = {
    "%REPLACE_ME_READER_PASS": "EXEC_HEALTH_FREEZE_READER_PASS",
    "%REPLACE_ME_WRITER_PASS": "EXEC_HEALTH_FREEZE_WRITER_PASS",
    "%REPLACE_ME_AUDIT_PASS": "EXEC_HEALTH_FREEZE_AUDIT_PASS",
    "%REPLACE_ME_BOOTSTRAP_PASS": "EXEC_HEALTH_FREEZE_BOOTSTRAP_PASS",
    "%REPLACE_ME_GO_GATEWAY_PASS": "GO_GATEWAY_REDIS_PASS",
    "%REPLACE_ME_EXEC_PROJECTION_PASS": "EXEC_PROJECTION_REDIS_PASS",
    "%REPLACE_ME_ENTRY_POLICY_SAFETY_PASS": "ENTRY_POLICY_SAFETY_REDIS_PASS",
    "%REPLACE_ME_LIQMAP_SNAPSHOT_PASS": "LIQMAP_SNAPSHOT_REDIS_PASS",
}


def _substitute_passwords(rules: List[str]) -> List[str]:
    """Replace %REPLACE_ME_*_PASS placeholders with values from ENV."""
    out: List[str] = []
    for token in rules:
        if token in _PASS_ENV:
            val = os.getenv(_PASS_ENV[token], "")
            if val:
                out.append(">" + val)
            else:
                out.append(token)  # keep placeholder if ENV not set; caller warns
        else:
            out.append(token)
    return out


def effective_rules(user: str) -> List[str]:
    """Return ACL rules for `user` with passwords substituted from ENV."""
    raw = list(EXPECTED_ACL_PROFILES.get(user, []))
    return _substitute_passwords(raw)


# ─── Redis connection helper ─────────────────────────────────────────────────

def _redis_client() -> Any:
    if redis is None:
        raise RuntimeError("redis package is not installed")
    # P20: validate runtime env contract before connecting
    assert_runtime_service_env_contract('exec_health_freeze_acl_policy_v1')
    url = os.getenv("EXEC_HEALTH_REDIS_BOOTSTRAP_URL") or os.getenv("REDIS_URL", "redis://redis-worker-1:6379/0")
    r = redis.Redis.from_url(url, decode_responses=True)
    ensure_service_identity_sync(r, "exec_health_freeze_acl_policy_v1")
    heal_service_identity_sync(r, "exec_health_freeze_acl_policy_v1", force=True)
    return r


# ─── Render ──────────────────────────────────────────────────────────────────

def render(stream: Any = None) -> None:
    """Print the full deployment contract to stdout (or stream)."""
    import io
    buf = stream or sys.stdout
    buf.write("# ExecHealth Freeze-Control — Redis ACL Deployment Contract (P12)\n")
    buf.write("# Generated by exec_health_freeze_acl_policy_v1.py render\n")
    buf.write("#\n")
    buf.write("# Apply with:\n")
    buf.write("#   python orderflow_services/exec_health_freeze_acl_policy_v1.py apply --reload-check\n")
    buf.write("#\n\n")
    for cmd in render_all_setuser_commands():
        buf.write(cmd + "\n")
    buf.write("\n# Service Identity Environment Templates:\n")
    buf.write(json.dumps(render_service_identity_env_templates(), indent=2) + "\n")
    buf.write("\n# Sensitive Deploy Env Templates (P20):\n")
    buf.write(json.dumps({'sensitive_deploy_env_templates': render_sensitive_deploy_env_templates()}, indent=2) + "\n")
    buf.write("\n# Verify:\n#   ACL LIST\n#   CONFIG GET aclfile\n")


# ─── Apply ───────────────────────────────────────────────────────────────────

def apply(reload_check: bool = True) -> Dict[str, Any]:
    """Apply ACL SETUSER for every expected user, then ACL SAVE.

    If reload_check is True, also runs ACL LOAD to verify persistence roundtrip.

    Returns a result dict:
      {ok, applied, failed, warnings, reload_ok}
    """
    r = _redis_client()
    heal_service_identity_sync(r, "exec_health_freeze_acl_policy_v1")
    assert_rollout_gate_open(r, purpose='exec_health_freeze_acl_policy_v1.apply', exit_code=24)
    applied: List[str] = []
    failed: List[str] = []
    warnings: List[str] = []

    for user in EXPECTED_USERS:
        rules = effective_rules(user)
        # warn if placeholder passwords remain
        unfilled = [t for t in rules if t.startswith("%REPLACE_ME_")]
        if unfilled:
            warnings.append(f"user {user}: unfilled password placeholders {unfilled}")
        try:
            r.execute_command("ACL", "SETUSER", user, *rules)
            applied.append(user)
        except Exception as exc:
            failed.append(user)
            warnings.append(f"ACL SETUSER {user} failed: {exc}")

    # Persist to aclfile (no-op if aclfile not configured in redis.conf)
    save_ok = False
    try:
        r.execute_command("ACL", "SAVE")
        save_ok = True
    except Exception as exc:
        warnings.append(f"ACL SAVE failed (aclfile may not be configured): {exc}")

    # Roundtrip check: reload from file, verify users are still present
    reload_ok: Optional[bool] = None
    if reload_check and save_ok:
        try:
            r.execute_command("ACL", "LOAD")
            # confirm all expected users still visible
            acl_lines: List[str] = r.execute_command("ACL", "LIST") or []
            present = {normalise_acl_line(ln)[0] for ln in acl_lines}
            reload_ok = all(u in present for u in EXPECTED_USERS)
            if not reload_ok:
                missing = [u for u in EXPECTED_USERS if u not in present]
                warnings.append(f"ACL LOAD roundtrip: missing users after reload: {missing}")
        except Exception as exc:
            warnings.append(f"ACL LOAD failed: {exc}")
            reload_ok = False

    ok = len(failed) == 0 and (reload_ok is not False)
    result: Dict[str, Any] = {
        "ok": ok,
        "applied": applied,
        "failed": failed,
        "warnings": warnings,
        "save_ok": save_ok,
        "reload_ok": reload_ok,
    }
    return result


# ─── Check / drift detection ─────────────────────────────────────────────────

def check() -> Dict[str, Any]:
    """Read ACL LIST, compare against expected contract, return drift report.

    Returns:
      {
        ok: bool,
        drift: bool,
        violations: list[str],          # human-readable violation descriptions
        per_user: dict[str, bool],       # user -> match (True = OK)
        default_off: bool,
        missing_users: list[str],
        raw_acl_list: list[str],
      }
    """
    r = _redis_client()
    heal_service_identity_sync(r, "exec_health_freeze_acl_policy_v1")
    raw_acl: List[str] = r.execute_command("ACL", "LIST") or []

    # Build map: username -> acl list line
    actual_map: Dict[str, str] = {}
    for line in raw_acl:
        user, _ = normalise_acl_line(line)
        if user:
            actual_map[user] = line

    violations: List[str] = []
    per_user: Dict[str, bool] = {}

    for user in EXPECTED_USERS:
        expected_rules = EXPECTED_ACL_PROFILES.get(user, [])
        if user not in actual_map:
            violations.append(f"user {user}: missing from ACL LIST")
            per_user[user] = False
            continue
        match = compare_acl(actual_map[user], expected_rules)
        per_user[user] = match
        if not match:
            violations.append(f"user {user}: ACL mismatch vs expected contract")

    # Check for unexpected users
    expected_set = set(EXPECTED_USERS)
    for user in actual_map:
        if user not in expected_set:
            violations.append(f"unexpected user in ACL LIST: {user}")

    default_off = is_default_user_disabled("\n".join(raw_acl))
    if not default_off:
        violations.append("default user is NOT disabled (must be off)")

    missing_users = [u for u in EXPECTED_USERS if u not in actual_map]

    drift = bool(violations)
    result: Dict[str, Any] = {
        "ok": not drift,
        "drift": drift,
        "violations": violations,
        "per_user": per_user,
        "default_off": default_off,
        "missing_users": missing_users,
        "raw_acl_list": raw_acl,
    }
    return result


# ─── CLI entrypoint ──────────────────────────────────────────────────────────

def main(argv: Optional[List[str]] = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    if not args or args[0] not in ("render", "apply", "check"):
        print("Usage: exec_health_freeze_acl_policy_v1.py {render|apply|check} [--reload-check]", file=sys.stderr)
        return 2

    cmd = args[0]

    if cmd == "render":
        render()
        return 0

    if cmd == "apply":
        reload_check = "--reload-check" in args
        result = apply(reload_check=reload_check)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0 if result["ok"] else 1

    if cmd == "check":
        result = check()
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0 if result["ok"] else 1

    return 2  # unreachable


if __name__ == "__main__":
    raise SystemExit(main())
